-- ========================================================
-- NetZeroCalc (e-Credits) Supabase Database Schema & Seed
-- ========================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID,
    project_name TEXT NOT NULL,
    company_name TEXT,
    standard TEXT DEFAULT 'ISO 14064-1 & Scope 1-3',
    total_footprint NUMERIC(12, 4) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bom_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    qty NUMERIC(12, 4) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    process TEXT,
    ef NUMERIC(12, 6) NOT NULL,
    scope VARCHAR(50) DEFAULT 'Scope 3',
    risk VARCHAR(20) DEFAULT 'LOW',
    status VARCHAR(50) DEFAULT 'Auto-Matched',
    approved BOOLEAN DEFAULT FALSE,
    ter NUMERIC(3, 1) DEFAULT 1.0,
    ger NUMERIC(3, 1) DEFAULT 1.0,
    tir NUMERIC(3, 1) DEFAULT 1.0,
    auditor_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.india_ghg_factors (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    lookup_key VARCHAR(255) UNIQUE NOT NULL,
    emission_factor NUMERIC(12, 6) NOT NULL,
    source_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bom_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.india_ghg_factors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access to projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to bom_items" ON public.bom_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access to india_ghg_factors" ON public.india_ghg_factors FOR ALL USING (true) WITH CHECK (true);

-- 60 Seeded India GHG Factors from GHG_Calculator_RECTIFIED_v6.xlsx
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Diesel_Fuel', 2.6558, 'India GHG Program base CO2 factor (2.64) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 2.6558 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Petrol_Fuel', 2.2836, 'India GHG Program base CO2 factor (2.27) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 2.2836 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('CNG_Fuel', 2.686, 'India GHG Program base CO2 factor (2.67) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 2.686 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('LPG_Commercial', 2.9979, 'India GHG Program base CO2 factor (2.98) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 2.9979 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Coal_Indian', 1.9919, 'India GHG Program base CO2 factor (1.98) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 1.9919 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Furnace_Oil', 3.1186, 'India GHG Program base CO2 factor (3.1) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 3.1186 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Natural_Gas', 1.8913, 'India GHG Program base CO2 factor (1.88) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 1.8913 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Acetylene_Welding', 3.4003, 'India GHG Program base CO2 factor (3.38) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 3.4003 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Fire_Extinguisher_CO2', 1.0, 'GWP of CO2 = 1, all AR vintages (kgCO2e/kg)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Refrig_R32', 675.0, 'IPCC AR4 GWP-100 (kgCO2e/kg) -- verify vintage required by your framework') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Refrig_R410A', 2088.0, 'IPCC AR4 GWP-100 (kgCO2e/kg) -- verify vintage required by your framework') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Refrig_R22', 1810.0, 'IPCC AR4 GWP-100 (kgCO2e/kg) -- verify vintage required by your framework') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Grid_India_CEA', 0.7314, 'India GHG Program base CO2 factor (0.727) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 0.7314 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Grid_MarketBased_Default', 0.7314, 'India GHG Program base CO2 factor (0.727) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 0.7314 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('REC_Backed_Electricity', 0.0, 'Renewable Energy Certificate / PPA-backed electricity, zero-rated per market-based method (kgCO2/kWh) -- confirm REC is unbundled and not double-counted') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Purchased_Steam', 0.1811, 'India GHG Program base CO2 factor (0.18) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 0.1811 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Transport_Truck_tkm', 0.09, 'India Road Logistics (kgCO2/tonne-km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Transport_LCV_km', 0.45, 'Light Commercial Vehicle (kgCO2/km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Transport_HGV_km', 0.85, 'Heavy Goods Vehicle (kgCO2/km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Rail_Freight', 0.015, 'Indian Railways Freight (kgCO2/tonne-km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Rail_Passenger', 0.01, 'Indian Railways Passenger (kgCO2/p-km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Air_Domestic', 0.12, 'Domestic Flights India (kgCO2/p-km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Air_International', 0.117, 'DEFRA/DESNZ 2025 UK Government GHG Conversion Factors -- long-haul economy, with radiative forcing (kgCO2e/passenger-km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Air_Freight_Cargo', 1.58, 'India GHG Program (kgCO2/tonne-km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Taxi_Diesel', 0.14, 'India GHG Program (kgCO2/km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Commute_2Wheeler', 0.04, 'Scooter/Bike Avg (kgCO2/km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Commute_Car_Avg', 0.14, 'Avg Small Car (kgCO2/km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Commute_Car_Small', 0.11, 'Small Car Segment (kgCO2/km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Commute_Car_Large', 0.17, 'Large Car Segment (kgCO2/km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Commute_Bus', 0.03, 'City Bus Service (kgCO2/p-km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Metro_Rail', 0.015, 'Metro Rail (kgCO2/p-km)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Waste_Landfill', 0.85, 'Indian Landfill Methane (kgCO2e/kg waste)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Waste_Recycle', 0.021, 'Transport energy only (kgCO2/kg)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Waste_Incineration', 0.4, 'India GHG Program estimate (kgCO2e/kg) -- verify locally') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Wastewater_Treatment', 0.708, 'India GHG Program (kgCO2/m3)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Water_Supply', 0.31, 'Cross-validated against international benchmarks: NZ Water Sector 2020/21 national methodology (~1.6-2.8 MJ/m3 energy intensity) and US LCA estimates (0.34-0.46 kgCO2/m3) both converge near this value -- no India-specific published factor exists; treat as an international proxy, not an India-measured figure') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Paper_Virgin', 0.92, 'India GHG Program (kgCO2/kg)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Paper_Recycled', 0.6, 'India GHG Program (kgCO2/kg)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Plastic_Packaging', 2.5, 'India GHG Program (kgCO2/kg)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Construction_Steel', 2.33, 'World Steel Association -- integrated mill (BOF) production route (kgCO2e/kg); India''s steel sector is majority BOF/integrated-mill with lower recycled content than EU/UK, so integrated-mill figure is the more representative default -- verify against specific supplier EPD where available') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Cement_Portland', 0.9, 'India GHG Program (kgCO2/kg)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Spend_IT', 0.005, 'Proxy: 5 tCO2 per Million INR spend') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Spend_Construction', 0.012, 'Proxy: 12 tCO2 per Million INR spend') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Spend_Generic_Services', 0.003, 'Proxy: 3 tCO2 per Million INR spend -- use only where no better data exists') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Laptop_Unit', 250.0, 'Embodied carbon per unit (kgCO2e/unit)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Desktop_Unit', 350.0, 'Embodied carbon per unit (kgCO2e/unit)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Smartphone_Unit', 65.0, 'Embodied carbon per unit (kgCO2e/unit)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Furniture', 3.5, 'Office furniture (kgCO2/kg)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Grid_TD_Loss', 0.1459, 'India GHG Program base CO2 factor (0.145) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 0.1459 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('WTT_Diesel', 0.5835, 'India GHG Program base CO2 factor (0.58) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 0.5835 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('WTT_Petrol', 0.4628, 'India GHG Program base CO2 factor (0.46) + ~0.6% CH4/N2O uplift per US EPA GHG Equivalencies methodology (2024) = 0.4628 kgCO2e -- uplift is a documented approximation (CO2 is >99% of combustion CO2e per EPA), not an India-specific measured N2O/CH4 split') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Hotel_5Star', 75.5, 'India GHG Program (kgCO2e/night)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Hotel_Budget', 25.0, 'India GHG Program (kgCO2e/night)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Product_Use_Phase_Energy', 0.0, 'PLACEHOLDER -- Category 11 (Use of Sold Products); populate with product-specific energy-use profile (kgCO2e/unit sold)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Product_EndOfLife', 0.0, 'PLACEHOLDER -- Category 12 (End-of-Life); populate with disposal-method-weighted factor (kgCO2e/unit sold)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Investment_Equity_Share', 0.0, 'PLACEHOLDER -- Category 15 (Investments); populate with equity-share-weighted investee emissions (kgCO2e/INR invested)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Franchise_Estimate', 0.0, 'PLACEHOLDER -- Category 14 (Franchises); populate with franchise-reported or estimated emissions (kgCO2e/franchise)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Leased_Asset_Downstream', 0.0, 'PLACEHOLDER -- Category 13 (Downstream Leased Assets); populate with lessee-reported energy use (kgCO2e/unit)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Financed_Emissions_Passthrough', 1.0, 'Direct pass-through of reported financed emissions (tCO2e/tCO2e)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;
INSERT INTO public.india_ghg_factors (lookup_key, emission_factor, source_notes) VALUES ('Processing_Sold_Products_Proxy', 0.0, 'PLACEHOLDER -- Category 10 (Processing of Sold Products); relevant only if selling intermediate goods for further processing; populate with downstream processor energy data (kgCO2e/unit sold)') ON CONFLICT (lookup_key) DO UPDATE SET emission_factor = EXCLUDED.emission_factor, source_notes = EXCLUDED.source_notes;