import { selectExportPeriod } from './ghg/inventoryAudit.js';
/**
 * openLCA JSON-LD Bridge Export Service
 * Serializes NetZeroCalc BOM-to-LCI mappings into an openLCA / ILCD compatible JSON-LD dataset.
 */

export function generateOpenLcaJsonLd(project, selectedYear) {
  const activePeriod = selectExportPeriod(project, selectedYear);

  const bom = activePeriod.bom || [];
  const processId = `process-${(project.id || 'e-credits-pcf').toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
  const productId = `flow-product-${(project.projectName || 'finished-product').toLowerCase().replace(/[^a-z0-9]/g, '-')}`;

  // Exchanges: 1 Quantitative Output (Finished Product) + N Technosphere/Elementary Inputs
  const exchanges = [
    {
      "@type": "Exchange",
      "internalId": 1,
      "flow": {
        "@type": "Flow",
        "@id": productId,
        "name": project.projectName || "Finished Product",
        "flowType": "PRODUCT_FLOW",
        "category": "Technosphere / Finished Goods"
      },
      "unit": {
        "@type": "Unit",
        "name": project.productionUnit || "Item"
      },
      "amount": project.productionVolume || 1,
      "isInput": false,
      "isQuantitativeReference": true,
      "description": "Finished product output from manufacturing cradle-to-gate life cycle boundary."
    }
  ];

  bom.forEach((item, idx) => {
    const exchangeId = idx + 2;
    const itemName = item.name || item.item || `Activity ${idx + 1}`;
    const isEnergy = (item.scope === 'Scope 2') || (item.item && itemName.toLowerCase().includes('electricity'));
    const isDirectFuel = (item.scope === 'Scope 1');

    exchanges.push({
      "@type": "Exchange",
      "internalId": exchangeId,
      "flow": {
        "@type": "Flow",
        "@id": `flow-input-${idx + 1}-${itemName.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
        "name": itemName,
        "flowType": "PRODUCT_FLOW",
        "category": isEnergy 
          ? "Technosphere / Electricity and Grid Mix" 
          : isDirectFuel 
            ? "Elementary / Resource / Fuel" 
            : "Technosphere / Raw Materials & Chemicals"
      },
      "unit": {
        "@type": "Unit",
        "name": item.unit || "kg"
      },
      "amount": Number(item.qty || 0),
      "isInput": true,
      "isQuantitativeReference": false,
      "dqEntry": formatPedigreeEntry(item.dqrPedigree || { r: 2, c: 2, t: 2, g: 2, te: 2 }),
      "comment": `Emission Factor: ${item.ef} ${item.efUnit || 'kg CO2e/unit'} | Source: ${item.efSource || item.sourceUrl || item.source || 'Not recorded'} | Scope: ${item.scope || 'Scope 3'}`
    });
  });

  const jsonLdProcess = {
    "@context": "http://greendelta.github.io/olca-schema/context.jsonld",
    "@type": "Process",
    "@id": processId,
    "name": `${project.companyName || 'Manufacturer'} - ${project.projectName || 'Product'} (Cradle-to-Gate)`,
    "version": "0.1.0",
    "lastChange": new Date().toISOString(),
    "processType": "UNIT_PROCESS",
    "description": "BOM-to-LCI cradle-to-gate inventory process generated by NetZeroCalc open-source mapping engine. Experimental screening bridge, not a complete LCIA database package. Validate and map flows in openLCA before use.",
    "infrastructureProcess": false,
    "processDocumentation": {
      "@type": "ProcessDocumentation",
      "timeDescription": activePeriod.periodName || activePeriod.label || `FY${activePeriod.year}`,
      "geographyDescription": project.geography || "India / Global",
      "technologyDescription": "Manufacturing Bill of Materials assembly and component conversion.",
      "intendedApplication": "Product Carbon Footprint (PCF) screening and internal baseline modeling.",
      "dataGenerator": {
        "@type": "Actor",
        "name": "NetZeroCalc Open-Source BOM-to-LCI Bridge",
        "description": "Automated openLCA schema exporter"
      }
    },
    "location": {
      "@type": "Location",
      "name": project.geography || "India",
      "code": project.geography === 'India' ? 'IN' : 'GLO'
    },
    "exchanges": exchanges
  };

  return jsonLdProcess;
}

export function downloadOpenLcaJsonLd(project, selectedYear) {
  const data = generateOpenLcaJsonLd(project, selectedYear);
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/ld+json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const safeName = (project.projectName || 'Project').replace(/[^a-z0-9]/gi, '_');
  a.download = `${safeName}_openLCA_Process_${new Date().toISOString().split('T')[0]}.jsonld`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function formatPedigreeEntry(pedigree) {
  const r = pedigree.r || 2;
  const c = pedigree.c || 2;
  const t = pedigree.t || 2;
  const g = pedigree.g || 2;
  const te = pedigree.te || 2;
  return `(${r};${c};${t};${g};${te})`;
}
