const escape = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json = value => escape(typeof value==='object' ? JSON.stringify(value,null,2) : value);
const link = value => {try {const u=new URL(value);return ['https:','http:'].includes(u.protocol)?`<a href="${escape(u.href)}" rel="noreferrer">${escape(value)}</a>`:escape(value)}catch{return escape(value)}};
export function customReportHtml(report){
 const total=n=>Number(n).toLocaleString('en-IN',{maximumFractionDigits:6});
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(report.title)}</title><style>
 body{font:15px/1.5 system-ui,sans-serif;color:#142b32;background:#f1f5f5;margin:0}main{max-width:1120px;margin:28px auto;background:white;padding:36px}h1{font-size:30px;line-height:1.15}h2{font-size:19px;margin-top:28px}p{max-width:85ch}.label{color:#52676e;font-size:12px;text-transform:uppercase;letter-spacing:.06em}.summary{display:flex;gap:24px;flex-wrap:wrap;border-top:3px solid #0d7660;border-bottom:1px solid #dce5e6;padding:18px 0}.summary strong{font-size:24px;display:block}.warning{padding:14px;background:#fff5de;border-left:4px solid #bf8a16}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:12px}td,th{padding:8px;border-bottom:1px solid #dce5e6;text-align:left;vertical-align:top;overflow-wrap:anywhere}th{background:#e8f2ef}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.5 system-ui}a{color:#086650}button{padding:10px;border:1px solid #0d7660;background:white;border-radius:6px;cursor:pointer}@media(max-width:600px){main{margin:0;padding:20px}h1{font-size:25px}}@media print{body{background:white}main{margin:0;padding:0;max-width:none}button{display:none}thead{display:table-header-group}tr{break-inside:avoid}.scroll{overflow:visible}a{color:inherit}table{font-size:9px}td,th{padding:5px}@page{size:A4 landscape;margin:14mm}}
 </style></head><body><main><button onclick="window.print()">Print / save as PDF</button><p class="label">NetZeroCalc · internal inventory report</p><h1>${escape(report.title)}</h1><p>${escape(report.company)} · ${escape(report.project)} · FY${escape(report.year)}</p><div class="summary"><div><span class="label">Selected emissions</span><strong>${total(report.totalTco2e)} tCO2e</strong></div><div><span class="label">Selected rows</span><strong>${report.rowCount}</strong></div><div><span class="label">Internal review flags</span><strong>${report.issues?.length??'Not checked'}</strong></div></div><p class="warning">${escape(report.disclaimer)}</p><h2>Selection and coverage</h2><pre>${json(report.filters)}</pre><p>${report.excludedRowCount??0} inventory rows excluded by filters. Selected totals do not represent the full inventory when filters exclude rows. Generated: ${escape(report.generatedAt)}.</p><h2>Scope breakdown</h2><table><thead><tr><th>Scope</th><th>Rows</th><th>tCO2e</th></tr></thead><tbody>${Object.entries(report.scopeTotals||{}).map(([scope,v])=>`<tr><td>${escape(scope)}</td><td>${v.rows}</td><td>${total(v.totalTco2e)}</td></tr>`).join('')}</tbody></table><h2>Narrative and limitations</h2><pre>${escape(report.narrative||'Not provided')}</pre><h2>Boundary and reporting notes</h2><pre>${json(report.boundary||'Not configured')}</pre><pre>${json(report.reportingNotes||{})}</pre><h2>Review flags</h2><p>Completeness checks only. An internal checkbox is not independent verification.</p><ul>${(report.issues||[]).map(i=>`<li>${escape(i.item)}: ${escape(i.detail)}</li>`).join('')||'<li>No flags detected by these limited internal checks.</li>'}</ul><h2>Row evidence</h2><div class="scroll"><table><thead><tr>${['Activity / quantity','Scope / facility','EF kgCO2e/unit','tCO2e','Factor evidence','Internal review'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${report.rows.map(r=>`<tr><td>${escape(r.name||r.item)}<br>${escape(r.qty)} ${escape(r.unit)}</td><td>${escape(r.scope)}<br>${escape(r.facilityId||'Not assigned')}</td><td>${escape(r.ef)}</td><td>${total(r.totalTco2e)}</td><td>${escape(r.source||r.efSource||'Not recorded')}<br>${link(r.sourceUrl||'')}<br>${escape(r.factorYear||'Year not recorded')} · ${escape(r.factorRegion||'Region not recorded')}<br>${escape(r.factorLicence||'Licence not recorded')} ${link(r.factorLicenceUrl||'')}<br>Boundary: ${escape(r.factorBoundary||'Not recorded')}<br>${r.proxy?'Proxy review required':'Proxy status not recorded'}</td><td>${r.approved?'Reviewed internally':'Unapproved'}<br>${escape(r.notes||'')}</td></tr>`).join('')}</tbody></table></div></main></body></html>`;
}
